name: ci

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Build and test
        uses: docker/build-push-action@v6
        with:
          context: app  # Define o contexto como o diretório 'app'
          target: test
          load: true
          file: app/Dockerfile  # Caminho para o Dockerfile
          
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: app  # Define o contexto como o diretório 'app'
          platforms: linux/amd64,linux/arm64/v8
          push: true
          target: prod
          tags: ${{ vars.DOCKER_USERNAME }}/${{ github.event.repository.name }}:latest
          file: app/Dockerfile  # Caminho para o Dockerfile
